channels:
  email: contact@full.dev
  # address: Kerkstraat 17, 9751BA Haren

# socials:
#   facebook: https://www.facebook.com/mignonbymarlieke
#   instagram: https://www.instagram.com/mignonbymarlieke/

header:
  heading: Fulldev UI
  variant: base
  links:
    - text: Home
      href: /
    - text: System
      href: /system
    - text: Components
      href: /components
    - text: Blocks
      href: /blocks
  buttons:
    - text: Github
      href: https://github.com/fulldotdev/ui
      target: _blank
      icon: brand-github
      variant: soft

    - text: Get Started
      href: /overview/introduction
      contrast: true
