spec:
  structures:
    - blocks
  label: Banner

blueprint:
  text:
  href:
  icon: arrow-right

preview:
  text: click here to go to the all new banner block
  icon: arrow-right
  href: /blocks/banner

_inputs:
