spec:
  structures:
    - blocks
  label: Categories

blueprint:
  heading:
  text:
  categories:
    - heading:
      text:
      href:
      image:

preview:
  heading: Shop by collection
  text: Handpicked collections for you.
  categories:
    - heading: Summer Collection
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /placeholder.webp
      href: '#'
    - heading: Summer Collection
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /placeholder.webp
      href: '#'
    - heading: Summer Collection
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /placeholder.webp
      href: '#'

_inputs:
