spec:
  label: Categories
  description: Een overzicht van product categorieën
  icon: category
  structures:
    - blocks

blueprint:
  heading:
  text:
  categories:
    - heading:
      text:
      href:
      image:
