spec:
  label: Collega's
  description: Een overzicht van collega's
  icon: recent_actors
  structures:
    - blocks

blueprint:
  heading:
  text:
  employees:
    - name:
      tagline:
      text:
      image:
