spec:
  label: Content
  description: Tekst, knoppen en een afbeelding
  icon: chrome_reader_mode
  structures:
    - blocks

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:
  image:
