spec:
  structures:
    - blocks
  label: Contact

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:

preview:
  heading: Contact Us!
  text: Do you have a question or need help with your order? We are here to help you. Please fill out the form below and we will get back to you as soon as possible.
  buttons:
    - text: Call us
  channels:
    - icon: phone
      title: Phone
      text: +31 123456789
      href: tel:+31 123456789
    - icon: mail
      title: Email
      text: example@example.com
      href: mailto:example@example.com
  socials:
    - icon: brand-facebook
      href: https://www.facebook.com/
    - icon: brand-instagram
      href: https://www.instagram.com/
    - icon: brand-x
      href: https://x.com/
_inputs:
