spec:
  structures:
    - blocks
  label: Content

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:
  image:

preview:
  heading: Lorem ipsum dolor sit amet
  text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  buttons:
    - text: Lorem ipsum
      href: '#'
    - text: Lorem ipsum
      href: '#'
  image: /placeholder.webp

_inputs:
