spec:
  structures:
    - blocks
  label: Cta

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:

preview:
  heading: Lorem ipsum dolor sit amet
  text: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  buttons:
    - text: Lorem ipsum
      href: '#'
    - text: Lorem ipsum
      href: '#'

_inputs:
