spec:
  structures:
    - blocks
  label: Employees

blueprint:
  heading:
  text:
  employees:
    - name:
      tagline:
      text:
      image:

preview:
  heading: Meet the team
  text: Our team of experts.
  employees:
    - name: John Doe
      tagline: CEO
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /avatar-placeholder.jpg
    - name: John Doe
      tagline: CEO
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /avatar-placeholder.jpg
    - name: John Doe
      tagline: CEO
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      image: /avatar-placeholder.jpg

_inputs:
