spec:
  structures:
    - blocks
  label: Features

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:
  cards:
    - icon:
      heading:
      text:

preview:
  heading: Fulldev-starter
  text: Get started with fulldev-starter by editing this page in src/content/pages/index.md.
  buttons:
    - text: Click me
      href: /
  cards:
    - icon: rocket
      heading: Ship websites fast
      text: Pre-built components used in pre-built blocks.
    - icon: pencil
      heading: Customize with ease
      text: Easily customize the look and feel of your website.
    - icon: typography
      heading: Repsonsive design
      text: Automatically cascades to fit any screen size.

_inputs:
