spec:
  structures:
  label: Footer

blueprint:
  logo:
  heading:
  href:
  buttons:
    - text:
      href:

preview:
  logo: /logo-placeholder.svg
  heading: Footer
  text: The best place to find pages.
  categories:
    - category: Legal
      links:
        - text: Terms Of Service
          href: /terms-of-service
        - text: Privacy Policy
          href: /privacy-policy
    - category: Products
      links:
        - text: Tees
          href: /tees
        - text: Hoodies
          href: /hoodies
        - text: Hoodies
          href: /hoodies

_inputs:
