spec:
  label: Header
  description: Een balk met links bovenaan de pagina
  icon: horizontal_rule
  structures:
    - header

blueprint:
  logo:
  heading:
  href:
  buttons:
    - text:
      href:
