spec:
  structures:
  label: Header

blueprint:
  logo:
  heading:
  href:
  buttons:
    - text:
      href:

preview:
  logo: /logo-placeholder.svg
  heading: Header
  links:
    - text: Link
      href: /
    - text: Blocks
      href: /blocks
  buttons:
    - text: Button
      href: /
    - text: Blocks
      href: /blocks

_inputs:
