spec:
  structures:
    - blocks
  label: Hero

blueprint:
  heading:
  text:
  buttons:
    - text:
      href:
  image:

preview:
  heading: Lorem ipsum dolor sit
  text: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  buttons:
    - text: Lorem ipsum
      href: '#'
    - text: Lorem ipsum
      href: '#'
  image: /placeholder.webp

_inputs:
