spec:
  structures:
    - blocks
  label: Intro

blueprint:
  heading:
  text:

preview:
  heading: Lorem ipsum dolor sit amet
  text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

_inputs:
