spec:
  structures:
    - blocks
  label: Logos

blueprint:
  heading:
  text:
  logos:
    -

preview:
  heading: Trusted by many
  text: Businesses such as name and name already use our services.
  logos:
    - /logo-placeholder.svg
    - /logo-placeholder.svg
    - /logo-placeholder.svg
    - /logo-placeholder.svg

_inputs:
