spec:
  structures:
    - blocks
  label: Missing

blueprint:
  tagline:
  heading:
  text:
  buttons:
    - text:
      href:
  links:
    - text:
      href:

preview:
  tagline: '404'
  heading: Page Not Found
  text: We could not find the page you were looking for.
  buttons:
    - text: Back to home
      href: /
  links:
    - text: Contact support
      href: /

_inputs:
