spec:
  structures:
    - blocks
  label: Newsletter

blueprint:
  heading:
  text:
  input:
    placeholder:
    button:

preview:
  heading: Never miss an update again..
  text: No actual emails get sent out as this is just another.
  input:
    placeholder: Enter your email..
    button: Subscribe

_inputs:
