spec:
  label: Blog posts
  description: Een overzicht van blog posts
  icon: view_carousel
  structures:
    - blocks

blueprint:
  heading:
  text:
  posts:
    - name:
      date:
      text:
      href:
      image:
      author:
        name:
        tagline:
        image:
