spec:
  structures:
    - blocks
  label: Posts

blueprint:
  heading:
  text:
  posts:
    - name:
      date:
      text:
      href:
      image:
      author:
        name:
        tagline:
        image:

preview:
  heading: Latest posts
  text: Read the latest articles from our blog.
  posts:
    - name: Summer Collection
      date: '2024-06-09'
      text: Today we have launched our new summer collection in europe. Ranging from new graphic tees to swim shorts. Check it out now!
      href: /
      image: /placeholder.webp
      author:
        name: John Doe
        tagline: Ceo @ Company
        image: /avatar-placeholder.jpg
    - name: Summer Collection
      date: '2024-06-09'
      text: Today we have launched our new summer collection in europe. Ranging from new graphic tees to swim shorts. Check it out now!
      href: /
      image: /placeholder.webp
      author:
        name: John Doe
        tagline: Ceo @ Company
        image: /avatar-placeholder.jpg
    - name: Summer Collection
      date: '2024-06-09'
      text: Today we have launched our new summer collection in europe. Ranging from new graphic tees to swim shorts. Check it out now!
      href: /
      image: /placeholder.webp
      author:
        name: John Doe
        tagline: Ceo @ Company
        image: /avatar-placeholder.jpg

_inputs:
