spec:
  structures:
    - blocks
  label: Prices

blueprint:
  tagline:
  heading:
  text:
  plans:
    - heading:
      text:
      price:
      features:
        - text:
      buttons:
        - text:
          href:

preview:
  tagline: Pricing
  heading: Choose the plan that suits you
  text: Our plans are designed to meet the requirements of both beginners and advanced users.
  plans:
    - heading: Free
      text: A free plan to help you get started
      price: $0
      features:
        - text: 1 GB of space
        - text: Support at $0
        - text: 1 email
        - text: 1 domain
      buttons:
        - text: Get started
          href: /
    - heading: Premium
      text: Suitable for small to medium businesses with a larger team
      price: $29
      features:
        - text: 10 GB of space
        - text: Support at $29
        - text: 10 email
        - text: 10 domain
      buttons:
        - text: Get started
          href: /
    - heading: Enterprise
      text: Our best plan for large companies with larger teams
      price: $99
      features:
        - text: 100 GB of space
        - text: Support at $99
        - text: 100 email
        - text: 100 domain
      buttons:
        - text: Get started
          href: /
        - text: Contact us
          href: /

_inputs:
