spec:
  structures:
    - blocks
  label: Product

blueprint:
  heading:
  price:
  rating:
  image:
  buttons:
    - text:
      href:
  paragraphs:
    - title:
      text:

preview:
  heading: 8 BALL TEE PIGMENT DYED
  price: €48
  rating: 5
  image: /placeholder.webp
  buttons:
    - text: Add to cart
      href: /
  subheading: Details
  description: Oversized tee in pigment dyed cotton with screenprinted graphics.
  list:
    - Shortsleeve
    - Ribbed collar
    - Runs large
    - Unisex
    - 'Material: 100% cotton'
    - Imported
_inputs:
