spec:
  structures:
    - blocks
  label: Products

blueprint:
  heading:
  text:
  products:
    - heading:
      description:
      price:
      image:

preview:
  heading: Best selling
  text: Our best selection of products.
  products:
    - heading: Product
      description: The best product in the world
      price: $100
      image: /placeholder.webp
      href: '#'
    - heading: Product
      description: The best product in the world
      price: $100
      image: /placeholder.webp
      href: '#'
    - heading: Product
      description: The best product in the world
      price: $100
      image: /placeholder.webp
      href: '#'
    - heading: Product
      description: The best product in the world
      price: $100
      image: /placeholder.webp
      href: '#'
    - heading: Product
      description: The best product in the world
      price: $100
      image: /placeholder.webp
      href: '#'
    - heading: Product
      description: The best product in the world
      price: $100
      image: /placeholder.webp
      href: '#'

_inputs:
