spec:
  structures:
    - blocks
  label: Reviews

blueprint:
  heading:
  text:
  cards:
    - rating:
      heading:
      paragraph:

preview:
  heading: Reviews
  text: Listen to what our customers are saying.
  cards:
    - rating: 5
      heading: Product A - Excellent Quality
      paragraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    - rating: 5
      heading: Product B - Outstanding Performance
      paragraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    - rating: 5
      heading: Product C - Amazing Features
      paragraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    - rating: 5
      heading: Product D - Exceptional Value
      paragraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    - rating: 5
      heading: Product E - Unmatched Reliability
      paragraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'

_inputs:
