spec:
  structures:
    - blocks
  label: Stats

blueprint:
  heading:
  text:
  stats:
    - heading:
      text:

preview:
  heading: Already up there
  text: We're already reached some milestones with even more to come.
  stats:
    - heading: 1000+
      text: Downloads
    - heading: 100+
      text: Contributors
    - heading: '1'
      text: Fork

_inputs:
