spec:
  label: Cards
  description: Een overzicht van kaartjes
  icon: description
  structures:
    - blocks

blueprint:
  heading:
  text:
  categories:
    - heading:
      text:
      href:
      image:
