spec:
  label: Pages
  description: Een overzicht van pagina's
  icon: description
  structures:
    - blocks

blueprint:
  heading:
  text:
  categories:
    - heading:
      text:
      href:
      image:
