title: Mignon by Marlieke
description: Tijdloze damesmode in hartverwarmend Haren
logo: /logo-placeholder.svg

channels:
  phone: 050-5348556
  email: info@mignon.nl
  address: Kerkstraat 17, 9751BA Haren

socials:
  facebook: https://www.facebook.com/mignonbymarlieke
  instagram: https://www.instagram.com/mignonbymarlieke/

hours:
  monday: Gesloten
  tuesday: 10:00 - 17:30
  wednesday: 10:00 - 17:30
  thursday: 10:00 - 17:30
  friday: 10:00 - 17:30
  saturday: 10:00 - 17:00
  sunday: Gesloten
