export default {
  paths: {
    uploads: 'public',
    static: 'public',
    uploads_filename: null,
    collections: null,
  },
  collections_config: {
    pages: {
      path: 'src/content/pages',
      output: true,
      url: '/[full_slug]/',
      filter: null,
      name: null,
      description: '',
      icon: 'wysiwyg',
      preview: {
        text: null,
        subtext: null,
        icon: null,
        icon_color: null,
        image: null,
        metadata: null,
        gallery: null,
      },
      _editables: null,
      _enabled_editors: ['visual', 'content'],
      _inputs: null,
      _select_data: null,
      _structures: null,
      create: {
        extra_data: null,
        publish_to: null,
        _inputs: null,
        _select_data: null,
        _structures: null,
      },
      disable_add: false,
      disable_add_folder: false,
      disable_file_actions: false,
      schemas: {
        '404': {
          path: 'src/schemas/404.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
        default: {
          path: 'src/schemas/page.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
        page: {
          path: 'src/schemas/page.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
        contact: {
          path: 'src/schemas/contact.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
        post: {
          path: 'src/schemas/post.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
        policy: {
          path: 'src/schemas/policy.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
        overview: {
          path: 'src/schemas/overview.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
        entry: {
          path: 'src/schemas/entry.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
      },
    },
    products: {
      path: 'src/content/products',
      output: true,
      url: '/producten/[full_slug]/',
      filter: null,
      name: null,
      description: '',
      icon: 'shopping_cart',
      preview: {
        text: null,
        subtext: null,
        icon: null,
        icon_color: null,
        image: null,
        metadata: null,
        gallery: null,
      },
      _editables: null,
      _enabled_editors: ['content', 'visual'],
      _inputs: null,
      _select_data: null,
      _structures: null,
      create: {
        extra_data: null,
        publish_to: null,
        _inputs: null,
        _select_data: null,
        _structures: null,
      },
      disable_add: false,
      disable_add_folder: false,
      disable_file_actions: false,
      schemas: {
        default: {
          path: 'src/schemas/product.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
      },
    },
    categories: {
      path: 'src/content/categories',
      output: true,
      url: '/categorieen/[full_slug]/',
      filter: null,
      name: null,
      description: '',
      icon: 'category',
      preview: {
        text: null,
        subtext: null,
        icon: null,
        icon_color: null,
        image: null,
        metadata: null,
        gallery: null,
      },
      _editables: null,
      _enabled_editors: ['content', 'visual'],
      _inputs: null,
      _select_data: null,
      _structures: null,
      create: {
        extra_data: null,
        publish_to: null,
        _inputs: null,
        _select_data: null,
        _structures: null,
      },
      disable_add: false,
      disable_add_folder: false,
      disable_file_actions: false,
      schemas: {
        default: {
          path: 'src/schemas/category.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
        },
      },
    },
    reviews: {
      path: 'src/content/reviews',
      output: false,
      name: null,
      description: '',
      icon: 'reviews',
      preview: {
        text: null,
        subtext: null,
        icon: 'reviews',
        icon_color: null,
        image: null,
        metadata: null,
        gallery: null,
      },
      _editables: null,
      _enabled_editors: ['data'],
      _inputs: null,
      _select_data: null,
      _structures: null,
      create: {
        extra_data: null,
        publish_to: null,
        _inputs: null,
        _select_data: null,
        _structures: null,
      },
      disable_add: false,
      disable_add_folder: false,
      disable_file_actions: false,
      schemas: {
        default: {
          path: 'src/schemas/review.md',
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
          _editables: null,
          _inputs: null,
          _select_data: null,
          _structures: null,
        },
      },
    },
    globals: {
      path: 'src/content/globals',
      output: false,
      name: null,
      description: '',
      icon: 'grid_view',
      preview: {
        text: null,
        subtext: null,
        icon: 'grid_view',
        icon_color: null,
        image: null,
        metadata: null,
        gallery: null,
      },
      _editables: null,
      _enabled_editors: ['data'],
      _inputs: null,
      _select_data: null,
      _structures: null,
      create: {
        extra_data: null,
        publish_to: null,
        _inputs: null,
        _select_data: null,
        _structures: null,
      },
      disable_add: false,
      disable_add_folder: false,
      disable_file_actions: false,
      schemas: {
        default: {
          reorder_inputs: true,
          hide_extra_inputs: true,
          remove_empty_inputs: true,
          remove_extra_inputs: false,
          icon: 'notes',
          _editables: null,
          _inputs: null,
          _select_data: null,
          _structures: null,
        },
      },
    },
  },
  collection_groups: [
    {
      heading: 'Pages',
      collections: ['pages', 'products', 'categories'],
    },
    {
      heading: 'Data',
      collections: ['reviews', 'globals'],
    },
  ],
  _inputs: {
    pages: {
      type: 'multiselect',
      options: {
        preview: {
          text: [
            {
              key: 'url',
            },
          ],
        },
      },
      label: 'Categorieën',
      cascade: true,
    },
    meta: {
      type: 'auto',
      label: 'SEO',
      cascade: true,
    },
    'meta.title': {
      type: 'auto',
      label: 'Pagina title',
      comment: '50 tot 60 karakters',
      cascade: true,
    },
    'meta.description': {
      type: 'auto',
      label: 'Pagina beschrijving',
      comment: '50 tot 120 karakters',
      cascade: true,
    },
    'meta.image': {
      type: 'auto',
      label: 'Pagina afbeelding',
      comment: 'Zichtbaar wanneer de pagina wordt gedeeld op social media',
      cascade: true,
    },
    image: {
      type: 'image',
      options: {
        mime_type: 'image/webp',
        resize_style: 'contain',
        width: 1920,
        height: 1920,
        expandable: false,
        sizes: [],
      },
      label: 'Afbeelding',
      cascade: true,
    },
    href: {
      type: 'url',
      label: 'Link',
      cascade: true,
    },
    rating: {
      type: 'range',
      options: {
        min: 0,
        max: 5,
        step: 0.1,
      },
      label: 'Rating',
      cascade: true,
    },
    images: {
      type: 'array',
      cascade: true,
    },
    logo: {
      type: 'image',
      cascade: true,
    },
    'images[*]': {
      type: 'image',
      options: {
        paths: null,
        mime_type: 'image/webp',
        empty_type: null,
        resize_style: 'contain',
        width: 1920,
        height: 1920,
        expandable: null,
        allowed_sources: null,
        prevent_resize_existing_files: null,
        sizes: null,
      },
      cascade: true,
    },
    draft: {
      type: 'switch',
      label: 'Concept',
      cascade: true,
    },
    variant: {
      type: 'auto',
      hidden: true,
      cascade: true,
    },
    price: {
      type: 'number',
      cascade: true,
    },
    paragraph: {
      type: 'textarea',
      cascade: true,
    },
  },
  _structures: {
    blocks: {
      remove_empty_inputs: true,
      style: 'modal',
    },
  },
  _editables: {
    content: {
      allow_custom_markup: false,
      remove_custom_markup: false,
      bold: true,
      bulletedlist: true,
      format: 'p h1 h2 h3 h4 h5 h6',
      image: true,
      image_size_attributes: true,
      italic: true,
      link: true,
      numberedlist: true,
      redo: true,
      table: true,
      underline: true,
      undo: true,
    },
  },
  timezone: 'Europe/Amsterdam',
  remove_empty_inputs: true,
}
